---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.0
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - dapper ci
- name: docker-publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    build_args:
    - ARCH=amd64
    repo: rancher/externalip-webhook
    tag: "${DRONE_TAG}-amd64"
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.5.0
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - dapper ci
- name: docker-publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    build_args:
    - ARCH=arm64
    repo: rancher/externalip-webhook
    tag: "${DRONE_TAG}-arm64"
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.5.0
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - dapper ci
- name: docker-publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    build_args:
    - ARCH=arm
    repo: rancher/externalip-webhook
    tag: "${DRONE_TAG}-arm"
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
---
kind: pipeline
name: manifest

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl
  when:
    instance:
    - drone-publish.rancher.io
    refs:
    - refs/head/master
    - refs/tags/*
    event:
    - tag
depends_on:
- amd64
- arm64
- arm
---
kind: pipeline
name: chart

steps:
- name: build
  image: rancher/dapper:v0.5.0
  environment:
    VERSION: ${DRONE_TAG}
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - dapper ./chart/ci
  when:
    event: tag
- name: github_prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - build/chart/rancher-externalip-webhook-*
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      include: [ refs/tags/*rc* ]
- name: github_release
  image: plugins/github-release
  settings:
    files:
    - build/chart/rancher-externalip-webhook-*
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
depends_on:
- manifest
